#!/bin/bash
if [[ ("$(nmcli r all | awk 'FNR == 2 {print $2}')" == "activé") || ("$(nmcli r all | awk 'FNR == 2 {print $2}')" == "enabled") ]]; then
	radio=On
else
	radio=Off
fi

choice=$(zenity --list --title "My Network Manager󰛳" --text="Click on the tool wanted" --column "Tools" ConnectionManager ConnectionEditor AirplaneModeSet${radio})
if [[ "${choice}" = "ConnectionManager" ]]; then
	connect.sh
elif [[ "${choice}" = "ConnectionEditor" ]]; then
	nm-connection-editor
elif [[ "${choice}" = "AirplaneModeSet${radio}" ]]; then
	if [[ "${radio}" = "On" ]]; then
		nmcli r wifi off
	else
		nmcli r wifi on
	fi
fi

exit 0
