#!/bin/sh
xrandr --output eDP --primary --mode "$(xrandr | grep primary | awk '{print $4}' | awk -F '+' '{print $1} ')" --pos 0x1024 --rotate normal --output HDMI-A-0 --mode 1280x1024 --pos 43x0 --rotate normal --output DisplayPort-0 --off --output DisplayPort-1 --off
wal -i ~/Images/dragon-girl.jpg >/dev/null

pactl set-default-sink "$(pactl list sinks | head -n 1 | awk '{print $2}' | sed -e "s/\#//g")"
